import { ShieldCheck } from 'lucide-react'
import ProtocolStatus from '../components/ProtocolStatus.jsx'
import RewardHistory from '../components/RewardHistory.jsx'
import RewardMechanism from '../components/RewardMechanism.jsx'
import Rewards from '../components/Rewards.jsx'
import WalletConnect from '../components/WalletConnect.jsx'
import { Reveal, Section, SectionHeader } from '../components/ui.jsx'
import PageShell from './PageShell.jsx'

export default function RewardsPage() {
  return (
    <>
      <PageShell
        eyebrow="Stock rewards"
        title="Your Stock Rewards"
        subtitle="Eligible MarketLens holders can track and claim stock-linked rewards generated by the protocol. Balances are read from the reward contract; claims are signed by your wallet."
        aside={<WalletConnect className="lg:mb-1" />}
      >
        <div className="grid gap-6 lg:grid-cols-12">
          <div className="space-y-6 lg:col-span-8">
            <Reveal>
              <Rewards />
            </Reveal>
            <Reveal delay={0.08}>
              <RewardHistory />
            </Reveal>
          </div>
          <div className="space-y-6 lg:col-span-4">
            <Reveal delay={0.05}>
              <ProtocolStatus />
            </Reveal>
            <Reveal delay={0.1}>
              <div className="card flex gap-3 p-5">
                <ShieldCheck className="mt-0.5 size-5 shrink-0 text-gold" strokeWidth={1.75} />
                <div className="text-sm">
                  <p className="font-semibold text-fg">Non-custodial by design</p>
                  <p className="mt-1 leading-relaxed text-muted">
                    MarketLens never holds your keys or funds. Reward accounting lives in the contract, and every claim is a
                    transaction you sign yourself.
                  </p>
                </div>
              </div>
            </Reveal>
          </div>
        </div>
      </PageShell>

      <Section id="mechanism" tone="tint">
        <Reveal>
          <SectionHeader
            eyebrow="How rewards work"
            title="From protocol fees to claimable rewards."
            subtitle="A transparent, verifiable path — no guesswork about where rewards come from."
          />
        </Reveal>
        <div className="mt-12">
          <RewardMechanism />
        </div>
      </Section>
    </>
  )
}
