import { Bell, FileText, Gift, Search } from 'lucide-react'
import FeatureCard from './FeatureCard.jsx'
import { Reveal, Section, SectionHeader } from './ui.jsx'

const FEATURES = [
  {
    icon: Search,
    title: 'Why Is It Moving?',
    description: "Understand what is driving a stock's movement by connecting market data, news, filings, and activity.",
    to: '/markets',
  },
  {
    icon: FileText,
    title: 'SEC & Filing Intelligence',
    description: 'Turn complex company filings into concise investor intelligence and identify what changed.',
    to: '/discover',
  },
  {
    icon: Bell,
    title: 'Smart Alerts',
    description: 'Get notified when something important happens across your watchlist.',
    to: '/alerts',
  },
  {
    icon: Gift,
    title: 'Stock Rewards',
    description: 'Eligible MarketLens holders can track and claim available stock-linked rewards generated by the protocol.',
    to: '/rewards',
  },
]

export default function FeaturesSection() {
  return (
    <Section id="features">
      <Reveal>
        <SectionHeader
          eyebrow="Platform"
          title="Everything You Need to Understand the Market"
          subtitle="MarketLens turns market data and financial information into clear intelligence."
        />
      </Reveal>
      <div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
        {FEATURES.map((f, i) => (
          <Reveal key={f.title} delay={i * 0.06}>
            <FeatureCard {...f} />
          </Reveal>
        ))}
      </div>
    </Section>
  )
}
