import { motion, useReducedMotion } from 'framer-motion'
import { ArrowDown, ArrowRight, BookOpenCheck, Coins, Landmark, ShoppingBag, Wallet, Zap } from 'lucide-react'
import { Reveal } from './ui.jsx'

const STEPS = [
  { icon: Zap, title: 'Protocol Fees', text: 'Fees generated by protocol activity accrue on-chain.' },
  { icon: Coins, title: 'Fee Collection', text: 'The off-chain keeper checks accumulated fees and execution conditions.' },
  { icon: Landmark, title: 'Reward Contract', text: 'Collected fees are transferred to the reward contract.' },
  { icon: ShoppingBag, title: 'Stock Acquisition', text: 'Configured swaps acquire the stock-linked reward assets.' },
  { icon: BookOpenCheck, title: 'Holder Accounting', text: 'Rewards are recorded per eligible holder and become claimable.' },
  { icon: Wallet, title: 'Claim Anytime', text: 'Holders claim with their own wallet whenever they choose.' },
]

/**
 * Elegant explanation of how protocol fees become claimable rewards.
 * Vertical flow on mobile, horizontal 6-step rail on desktop. Copy only — no figures.
 */
export default function RewardMechanism({ compact = false }) {
  const reduce = useReducedMotion()

  return (
    <div>
      <ol className={`grid gap-3 ${compact ? 'lg:grid-cols-3' : 'lg:grid-cols-6'}`}>
        {STEPS.map((s, i) => {
          const Icon = s.icon
          const last = i === STEPS.length - 1
          return (
            <li key={s.title} className="relative">
              <motion.div
                initial={reduce ? false : { opacity: 0, y: 14 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: '-40px' }}
                transition={{ duration: 0.5, delay: i * 0.08, ease: [0.22, 1, 0.36, 1] }}
                className="card flex h-full flex-row items-start gap-4 p-4 lg:flex-col lg:gap-3 lg:p-5"
              >
                <span className="relative inline-flex size-10 shrink-0 items-center justify-center rounded-xl bg-light text-blue">
                  <Icon className="size-4.5" strokeWidth={1.75} />
                  <span className="tabular absolute -top-1.5 -right-1.5 inline-flex size-5 items-center justify-center rounded-full bg-navy text-[10px] font-bold text-white">
                    {i + 1}
                  </span>
                </span>
                <div className="min-w-0">
                  <p className="text-sm font-bold tracking-tight text-navy">{s.title}</p>
                  <p className="mt-1 text-xs leading-relaxed text-muted">{s.text}</p>
                </div>
              </motion.div>

              {!last && (
                <>
                  {/* mobile connector */}
                  <span aria-hidden="true" className="flex justify-center py-1 text-blue/60 lg:hidden">
                    <ArrowDown className="size-4" />
                  </span>
                  {/* desktop connector */}
                  {!compact && (
                    <span
                      aria-hidden="true"
                      className="absolute top-1/2 -right-[7px] z-10 hidden size-4 -translate-y-1/2 items-center justify-center rounded-full bg-bg text-blue/70 lg:flex"
                    >
                      <ArrowRight className="size-3.5" />
                    </span>
                  )}
                </>
              )}
            </li>
          )
        })}
      </ol>

      <Reveal delay={0.2}>
        <p className="mx-auto mt-8 max-w-2xl text-center text-sm leading-relaxed text-muted">
          Protocol fees are processed through the reward infrastructure and recorded as claimable rewards for eligible
          holders. Distribution timing depends on accumulated fees and network conditions; every step is verifiable on-chain.
        </p>
      </Reveal>
    </div>
  )
}
